version: '3.8'

services:

  db:
    image: postgres:14
    container_name: tol_postgres

    environment:
      POSTGRES_DB: tol_pagos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .

    container_name: tol_app

    ports:
      - "8080:8080"

    depends_on:
      - db

    environment:
      DB_URL: jdbc:postgresql://db:5432/tol_pagos
      DB_USER: postgres
      DB_PASSWORD: 1234

volumes:
  pgdata: